info:
  contact: {}
  description: This is the course forum api documentation
  license:
    name: MIT License
    url: https://github.com/Kevin-Shen-and-Cipher/course-forum-forum-servcie/blob/main/LICENSE
  title: Course forum API
  version: "1.0"
paths: {}
swagger: "2.0"
